#server:
#    port: 8082
#
#spring:
#    h2:
#        console:
#            enabled: true
#            path: /h2_db
#
#datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./h2_db;AUTO_SERVER=TRUE
#    username: sa
#    password: root
